services:
  diffusion:
    image: whoatemyapplepie/stable-diffusion:cpu
    build: ./docker_build
    container_name: sdw
    volumes:
      - $PWD/src:/src
      - $PWD/output:/output
    working_dir: /work
    env_file:
      - ".env"
    command:
      - /bin/bash
      - -c
      - |
        cp -f /src/gen_image.py /work/
        source /work/mochiai/bin/activate
        python3 gen_image.py "${REQ}"
        mv /work/*.png /output/
    tty: true
